In [1]:
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

X = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [3, 4, 5, 6],
    [4, 5, 6, 7],
    [5, 6, 7, 8],
    [6, 7, 8, 9],
    [7, 8, 9, 10],
    [8, 9, 10, 11]
], dtype=float)

X = X / 10

input_layer = Input(shape=(4,))

encoded = Dense(2, activation="relu")(input_layer)

decoded = Dense(4, activation="sigmoid")(encoded)

autoencoder = Model(input_layer, decoded)

encoder = Model(input_layer, encoded)

autoencoder.compile(optimizer="adam", loss="mse")

autoencoder.fit(X, X, epochs=200, verbose=0)

reduced_data = encoder.predict(X, verbose=0)

print("Original Data:")
print(X)

print("\nReduced Data:")
print(reduced_data)

print("Name: Omkar Vaidya")
print("Roll No.: 40")

Original Data:
[[0.1 0.2 0.3 0.4]
 [0.2 0.3 0.4 0.5]
 [0.3 0.4 0.5 0.6]
 [0.4 0.5 0.6 0.7]
 [0.5 0.6 0.7 0.8]
 [0.6 0.7 0.8 0.9]
 [0.7 0.8 0.9 1. ]
 [0.8 0.9 1.  1.1]]

Reduced Data:
[[0.         0.00314283]
 [0.         0.02220853]
 [0.         0.0412742 ]
 [0.         0.0603399 ]
 [0.         0.07940558]
 [0.         0.09847127]
 [0.         0.11753695]
 [0.         0.13660266]]
Name: Omkar Vaidya
Roll No.: 40
